name: Production bot deployment via SSH

on:
    push:
        branches: [production]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: SSH into VM
              uses: fifsky/ssh-action@master
              with:
                  command: |
                      cd halo-discord-bot
                      git checkout production
                      git reset --hard origin/production
                      git pull
                      pnpm i --frozen-lockfile
                      pnpx pm2 delete all
                      pnpm run deploy
                  host: ${{ secrets.SSH_HOST }}
                  user: eli_olmos9
                  key: ${{ secrets.SSH_PRIVATE_KEY}}
                  args: '-vvv'
