name: Check License Header

on:
    push:
    pull_request:

jobs:
    detect-duplicate:
        name: detect-duplicate
        runs-on: ubuntu-latest
        outputs:
            should_skip: ${{ steps.skip_check.outputs.should_skip }}
        steps:
            - name: Detect Duplicate
              id: skip_check
              uses: fkirc/skip-duplicate-actions@master
              with:
                  paths_ignore: '["**.md", "**.mdx", "**.png", "**.jpg"]'
                  do_not_skip: '["workflow_dispatch", "schedule"]'
    check-license-header:
        name: check-license-header
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Fix License Header
              uses: apache/skywalking-eyes/header@main
              with:
                  mode: fix
                  log: info
                  config: .github/config/.licenserc.yml
            - name: Apply Changes
              uses: EndBug/add-and-commit@v9
              with:
                  default_author: github_actions
                  message: 'chore(license): add license header to files'
